ln -sf .bashrc "$HOME/.bashrc"
ln -sf .bashrc_ssh "$HOME/.bashrc_ssh"
ln -sf .config "$HOME/.config"
ln -sf .dircolors "$HOME/.dircolors"
ln -sf .fonts "$HOME/.fonts"
ln -sf .gitignore "$HOME/.gitignore"
ln -sf .prompt.bash "$HOME/.prompt.bash"
ln -sf .vimrc "$HOME/.vimrc"
